name: item_scanner
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  
  flutter_archive: ^5.0.0
  file_picker: ^6.1.1

  # Internal packages
  logging_util:
    path: ../packages/logging_util
  ui_design_system:
    path: ../packages/ui_design_system
  service_network:
    path: ../packages/service_network

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
